### PR TITLE
Eulerian path

### LINKED ISSUE #11: Challenge: Eulerian_path

### PR DESCRIPTION
**Pull request by KhalidOmer**
- [x] PR's title includes the challenge's name and language
- [x] PR has short and clear description of the challenge
- [ ] PR has appropriate labels and milestones for easy identification
- [ ] PR it is assigned to the owner
- [x] reviewers are assigned
- [x] the PR contributes only one focused change
- [ ] the branch is up to date with `main`/`master`
- [ ] the code works when pulled and run locally
- [ ] all conflicts are resolved (if any)
- [ ] It is linked to an issue in the appropriate column of the project board
- [ ] feedback is addressed (if any, and if it is appropriate feedback.)

## README Documentation

- [x] The solution is documented in `/src/README.md`
- [x] The markdown source is formatted
- [ ] Spelling and grammar is correct in all text
- [x] The markdown looks correct when you preview the file
- [ ] All links and images work
- [x] The README documents the solution's behavior, strategy(ies) and implementation(s)
- [ ] There are use cases in code blocks to illustrate the function's behavior

## Python Files

- [ ] There is a module header
- [x] There is a module docstring
- [x] File names are in snake_case
- [x] Test files are named `test_<module_name>.py`

## Function Docstring

- [ ] Behavior description
- [ ] Parameter description
- [ ] Return value description
- [ ] Include any assumptions
- [ ] Include 3 or more (passing!) doctests
- [ ] Include 1-2 use cases (if necessary)

## Function Implementation

- [ ] The solution is not is not copied from [djeada](https://github.com/djeada/Algorithms-And-Data-Structures)
- [ ] The code is auto-formatted
- [ ] The code has no (reasonable) linting mistakes
- [ ] Variables are named with snake_case
- [ ] The function has a clear and helpful name
- [ ] The file's name matches the function name
- [ ] The code follows the strategy as simply as possible
- [ ] Variable names are clear and helpful
- [ ] Comments explain the strategy (if necessary)
- [ ] There are type annotations
- [ ] (challenge) The code includes defensive assertions

## Unit Test Suite

- [ ] The test class has a helpful name in PascalCase
- [ ] The test class has a docstring
- Each unit test has
  - [ ] A helpful name
  - [ ] A clear docstring
  - [ ] Only one assertion
- [ ] All tests pass
- [ ] There are tests for defensive assertions
- [ ] There are tests for boundary cases
- [ ] Test suite includes black-box and glass-box tests

### CODE REVIEW

**Comment by KhalidOmer** [comment]
I used three files for coding this problem, the main file eulerian_path.py, also a file that the helper functions I used is_connected.py and the test file test_eulerian_path.py

**Comment by joshuaSamuel06** [comment]
Your current code is not passing the testcases already present in the file. Also, kindly update your branch with the main branch and then add your code.

**Review by joshuaSamuel06 — COMMENTED** [review]
Your branch is not up to date with the main branch. Also, your function is not passing the testcases present in the tests folder.

**Comment by KhalidOmer** [comment]
The unittest is now fixed

**Pull request merged**
